version: '3.8'
services:
  ecommerce-client:
    build:
      context: .
      network: fullstack-ecommerce-server_default
    image: karta0989006/ecommerce-client  
    ports:
      - 3000:3000
    networks:
      - fullstack-ecommerce-server_default
    # command: ["npm", "run", "dev"] 
    command: ["npm", "start"]


networks:
  fullstack-ecommerce-server_default:
    external:
      name: fullstack-ecommerce-server_default

